In [1]:
# import libraries
import numpy as np
import torch

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.77 -2.59 -5.99 -5.42  0.44]
 [-8.77 -0.36 -0.96 -6.8   0.94]
 [ 1.18  0.69 -1.49  0.53  1.25]]
 
[[-0.31  1.68 -2.22 -0.4 ]
 [ 1.94 -0.73  2.46  0.11]
 [-0.14 -2.05  2.29  0.11]
 [-0.33  0.97 -1.5   2.33]
 [-0.55 -2.84  2.84  1.45]
 [ 0.82  3.8  -4.02  5.87]
 [ 0.29 -3.06  3.76  2.05]]


In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-3.0300, -1.1200,  2.6000,  1.3300, -0.6000, -1.8000, -1.1100],
        [-0.8700, -0.5400,  1.5600, -0.2900, -0.3900, -1.5100, -0.5300],
        [ 1.0400,  2.0400, -0.0200,  0.1200,  1.0400, -0.1700, -0.0600]],
       dtype=torch.float64)
 
tensor([[-3.0300, -1.1200,  2.6000,  1.3300, -0.6000, -1.8000, -1.1100],
        [-0.8700, -0.5400,  1.5600, -0.2900, -0.3900, -1.5100, -0.5300],
        [ 1.0400,  2.0400, -0.0200,  0.1200,  1.0400, -0.1700, -0.0600]])
