In [2]:
# import libraries
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

In [3]:
# create a vector
v = np.array([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40


In [4]:
# repeat with matrix
M = np.array([ [0,1,10], [20,8,5] ])
print(M), print(' ')

# various minima in this matrix!
minvals1 = np.min(M)        # minimum from ENTIRE matrix
minvals2 = np.min(M,axis=0) # minimum of each column (across rows)
minvals3 = np.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


# Pytorch

In [5]:
# create a vector
v = torch.tensor([ 1,40,2,-3 ])

# find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print('Min,max: %g,%g' %(minval,maxval) )


# now for the argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min,max indices: %g,%g' %(minidx,maxidx) ), print(' ')

# confirm
print(f'Min val is { v[minidx] }, max val is { v[maxidx] }')

Min,max: -3,40
Min,max indices: 3,1
 
Min val is -3, max val is 40


In [6]:
# repeat with matrix
M = torch.tensor([ [0,1,10], [20,8,5] ])
print(M), print(' ')

# various minima in this matrix!
min1 = torch.min(M)        # minimum from ENTIRE matrix
min2 = torch.min(M,axis=0) # minimum of each column (across rows)
min3 = torch.min(M,axis=1) # minimum of each row (across columns)

# print them out
print(min1), print(' ')
print(min2), print(' ')
print(min2.values)
print(min2.indices)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
tensor([0, 0, 1])
